[package]
name = "InitiaStdlib"
version = "1.0.0"

[dependencies]
# MoveStdlib = { git = "https://github.com/initia-labs/initiavm.git", subdir = "precompile/modules/move_stdlib", rev = "main" }
# MoveNursery = { git = "https://github.com/initia-labs/initiavm.git", subdir = "precompile/modules/move_nursery", rev = "main" }
MoveStdlib = { local = "../../../../initiavm/precompile/modules/move_stdlib" }
MoveNursery = { local = "../../../../initiavm/precompile/modules/move_nursery" }

[addresses]
std = "0x1"
initia_std = "0x1"
addr = "0x4fb9c533eb3f279c2d61ca206a86aa4c2eb20f3"